###############################################
# MediaMTX Configuration for NOMAD
# 
# Ultra-low latency configuration for FPV drone operations.
# Optimized for <150ms glass-to-glass latency.
#
# Source: https://github.com/bluenviron/mediamtx
###############################################

# ============================================================
# Global Settings - LOW LATENCY OPTIMIZED
# ============================================================

# Logging level (debug, info, warn, error)
logLevel: warn
logDestinations: [stdout]

# Minimal timeouts for low latency
readTimeout: 5s
writeTimeout: 5s
writeQueueSize: 64  # Smaller buffer = lower latency

# ============================================================
# API (for monitoring)
# ============================================================

api: yes
apiAddress: :9997
# Metrics for Prometheus
metrics: yes
metricsAddress: :9998

# ============================================================
# RTSP Server - LOW LATENCY OPTIMIZED
# ============================================================

rtsp: yes
rtspAddress: :8554
protocols: [udp, tcp]  # UDP first for lower latency

# Disable RTSP authentication for local/Tailscale access
rtspAuthMethods: []

# ============================================================
# RTMP Server (disabled)
# ============================================================

rtmp: no
rtmpAddress: :1935

# ============================================================
# HLS Server (disabled)
# ============================================================

hls: no
hlsAddress: :8888

# ============================================================
# WebRTC Server (disabled - using RTSP for Mission Planner)
# ============================================================

webrtc: no
webrtcAddress: :8889

# ============================================================
# SRT Server (disabled)
# ============================================================

srt: no
srtAddress: :8890

# ============================================================
# Recording (optional)
# ============================================================

record: no

# ============================================================
# Paths (stream endpoints) - ZED2i Multi-Camera Views
# ============================================================

paths:
  # ZED2i stream from RTP/UDP
  # GStreamer sends H264 RTP packets to UDP port 8000
  # MediaMTX listens and re-publishes as RTSP
  zed:
    source: udp+rtp://localhost:8000
    # Disable authentication
    publishUser:
    publishPass:
    readUser:
    readPass:
    # SDP for H264 RTP stream
    rtpSDP: |
      v=0
      o=- 0 0 IN IP4 127.0.0.1
      s=ZED Camera Stream
      c=IN IP4 127.0.0.1
      t=0 0
      m=video 8000 RTP/AVP 96
      a=rtpmap:96 H264/90000

  # Alternative endpoint for direct RTSP publish
  live:
    source: publisher
    publishUser:
    publishPass:
    readUser:
    readPass:

  # Wildcard path - accept any stream name
  all:
    source: publisher
    publishUser:
    publishPass:
