#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The NOMAD Authors
"""Generate MAVLink C headers from the pinned ArduPilot mavlink submodule.

NOMAD's MAVLink codec (src/mavlink/) compiles against these generated headers
instead of hand-maintained dialect tables. The headers are generated from
third_party/ardupilot-mavlink, pinned to the exact commit the ArduPilot
firmware release compiles against, so message ids, crc_extras, lengths, and
field layouts always match the firmware.

The generated output is a build artifact: it lives under build/generated/mavlink
(gitignored) and must never be committed. Regenerate after every ArduPilot
version bump by updating the submodule pin and running:

    pixi run generate-mavlink
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def find_submodule(root: Path) -> Path:
    mavlink = root / "third_party" / "ardupilot-mavlink"
    mavgen = mavlink / "pymavlink" / "tools" / "mavgen.py"
    xml = mavlink / "message_definitions" / "v1.0" / "ardupilotmega.xml"
    if not mavgen.is_file() or not xml.is_file():
        sys.exit("error: MAVLink submodule is not initialized. Run:\n  git submodule update --init --recursive")
    return mavlink


def is_up_to_date(mavlink: Path, output: Path) -> bool:
    provenance = output / "provenance.txt"
    dialect = output / "common" / "common.h"
    if not provenance.is_file() or not dialect.is_file():
        return False
    commit = subprocess.run(
        ["git", "-C", str(mavlink), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    return f"Source: third_party/ardupilot-mavlink @ {commit}" in provenance.read_text()


def generate_headers(mavlink: Path, output: Path) -> int:
    output.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env["PYTHONPATH"] = str(mavlink) + os.pathsep + env.get("PYTHONPATH", "")
    command = [
        sys.executable,
        str(mavlink / "pymavlink" / "tools" / "mavgen.py"),
        "--lang=C",
        "--wire-protocol=2.0",
        f"--output={output}",
        str(mavlink / "message_definitions" / "v1.0" / "ardupilotmega.xml"),
    ]
    print(f"Generating MAVLink C headers from {mavlink}")
    return subprocess.run(command, env=env).returncode


def write_provenance(mavlink: Path, output: Path) -> None:
    commit = subprocess.run(
        ["git", "-C", str(mavlink), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    provenance = output / "provenance.txt"
    provenance.write_text(
        "Generated by scripts/dev/generate_mavlink.py\n"
        f"Source: third_party/ardupilot-mavlink @ {commit}\n"
        "XML: message_definitions/v1.0/ardupilotmega.xml\n"
        f"Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    default_output = repo_root() / "build" / "generated" / "mavlink"
    parser.add_argument(
        "--output", type=Path, default=default_output, help="output directory (default: build/generated/mavlink)"
    )
    args = parser.parse_args()

    mavlink = find_submodule(repo_root())
    if is_up_to_date(mavlink, args.output):
        print(f"MAVLink headers up to date in {args.output}")
        return 0
    result = generate_headers(mavlink, args.output)
    if result != 0:
        return result
    write_provenance(mavlink, args.output)
    print(f"MAVLink headers generated in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
